      - name: Render first page to PNG(s) with debug
        run: |
          echo "Listing current working directory:"
          pwd
          ls -R

          echo "Checking editions/latest.pdf..."
          if [ ! -f editions/latest.pdf ]; then
            echo "ERROR: editions/latest.pdf not found"
            exit 1
          fi

          ls -lh editions/latest.pdf

          echo "Rendering at 1200px..."
          pdftoppm -png -f 1 -l 1 -scale-to 1200 editions/latest.pdf editions/latest-teaser-1200 || { echo "pdftoppm 1200 failed"; exit 1; }
          ls -l editions/latest-teaser-1200*.png || echo "No 1200px PNG produced"

          echo "Rendering at 2000px..."
          pdftoppm -png -f 1 -l 1 -scale-to 2000 editions/latest.pdf editions/latest-teaser-2000 || { echo "pdftoppm 2000 failed"; exit 1; }
          ls -l editions/latest-teaser-2000*.png || echo "No 2000px PNG produced"

          echo "Renaming outputs..."
          if [ -f editions/latest-teaser-1200-1.png ]; then
            mv editions/latest-teaser-1200-1.png editions/latest-teaser-1200.png
          else
            echo "1200 PNG not found to rename"
            exit 1
          fi
          if [ -f editions/latest-teaser-2000-1.png ]; then
            mv editions/latest-teaser-2000-1.png editions/latest-teaser-2000.png
          else
            echo "2000 PNG not found to rename"
            exit 1
          fi

          echo "Optimizing..."
          pngquant --force --output editions/latest-teaser-1200.png editions/latest-teaser-1200.png
          pngquant --force --output editions/latest-teaser-2000.png editions/latest-teaser-2000.png

          echo "Generated teaser images:"
          ls -lh editions/latest-teaser-*.png
on:
  push:
    paths:
      - 'editions/latest.pdf'   # run only when latest.pdf changes

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poppler (pdftoppm) + pngquant
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils pngquant

      - name: Render first page of latest.pdf to PNG(s)
        run: |
          # Render page 1 at two useful sizes for crisp displays
          pdftoppm -png -f 1 -l 1 -scale-to 1200 editions/latest.pdf editions/latest-teaser-1200
          pdftoppm -png -f 1 -l 1 -scale-to 2000 editions/latest.pdf editions/latest-teaser-2000

          # Rename outputs (pdftoppm appends -1 to the filename)
          mv editions/latest-teaser-1200-1.png editions/latest-teaser-1200.png
          mv editions/latest-teaser-2000-1.png editions/latest-teaser-2000.png

          # Optional: lossless-ish optimization
          pngquant --force --output editions/latest-teaser-1200.png editions/latest-teaser-1200.png
          pngquant --force --output editions/latest-teaser-2000.png editions/latest-teaser-2000.png

      - name: Commit teaser image(s)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-generate latest front-page teaser images"
          file_pattern: |
            editions/latest-teaser-1200.png
            editions/latest-teaser-2000.png
